name: Build and Deploy
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: kamranahmedse/github-pages-blog-action@v0.0.10
        with:
          branch: gh-pages
          token: ${{ secrets.GH_TOKEN }}  # Use the new secret
